# Generated by Django 5.0.6 on 2024-06-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportcardapp', '0002_alter_subjectmarks_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id'], 'verbose_name': 'student'},
        ),
    ]
