# Generated by Django 5.0.6 on 2024-06-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportcardapp', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_name'], 'verbose_name': 'student'},
        ),
    ]
