# Generated by Django 5.0.6 on 2024-06-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportcardapp', '0004_alter_student_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_rank', models.IntegerField(default=0)),
                ('date_of_report_generation', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentrank', to='reportcardapp.student')),
            ],
            options={
                'unique_together': {('student_rank', 'date_of_report_generation')},
            },
        ),
    ]
