# Generated by Django 5.0.6 on 2024-06-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportcardapp', '0005_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='date_of_report_generation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
