# Generated by Django 5.0.6 on 2024-06-22 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportcardapp', '0006_alter_rank_date_of_report_generation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_department'], 'verbose_name': 'student'},
        ),
    ]
